[env:esp32-c5-supermini]
extends = env_4mb

board = esp32-c5-supermini
board_build.partitions = custom_4Mb.csv

build_src_filter = ${env.build_src_filter} +<../boards/esp32-c5-supermini>

build_flags =
        ${env_4mb.build_flags}

        -Iboards/esp32-c5-supermini
        -DESP32C5_SUPERMINI=1
        -DDEVICE_NAME='"ESP32-C5 SuperMini"'

        -DARDUINO_USB_CDC_ON_BOOT=1
        -DARDUINO_USB_MODE=1
        -DCORE_DEBUG_LEVEL=1

        -DALLOW_ALL_GPIO_FOR_IR_RF=1

        -DFP=1
        -DFM=2
        -DFG=3
        -DBTN_ALIAS='"OK"'
        -DBRUCE_VERSION='"dev"'
        -DEEPROMSIZE=128
        -DLH=8
        -DLW=6 

        ; TFT ST7735 128x160
        -DST7735_DRIVER=1
        -DST7735_GREENTAB=1
        -DTFT_WIDTH=128
        -DTFT_HEIGHT=160

        ; FM Radio
        -DFM_SI4713=1