[env:esp32-c5-supermini]
board = esp32-c5-supermini
board_build.partitions = custom_4Mb.csv

build_src_filter =
        ${env.build_src_filter}
        +<../boards/ESP32-C5-supermini>

build_flags =
        ${env.build_flags}
        -Iboards/ESP32-C5-supermini
        -DDEVICE_NAME='"ESP32-C5 SuperMini"'
        -DESP32C5_SUPERMINI=1
        -DARDUINO_USB_CDC_ON_BOOT=1
        -DARDUINO_USB_MODE=1
        -DCORE_DEBUG_LEVEL=1

        ; Allow GPIO selection for IR/RF
        -DALLOW_ALL_GPIO_FOR_IR_RF=1

        ; text sizes
        -DFP=1
        -DFM=2
        -DFG=3

        ; UI
        -DBTN_ALIAS='"OK"'
